export const ADD_SET = 'ADD_SET'
export const LBS_INPUT_CHANGE = 'LBS_INPUT_CHANGE'
export const REPS_INPUT_CHANGE = 'REPS_INPUT_CHANGE'

export const CREATE_COMMUNITY = 'CREATE_COMMUNTIY'
export const POST_STATUS = 'POST_STATUS'
export const SWITCH_COMMUNITY = 'SWITCH_COMMUNITY'
export const ADD_ACTIVITY = 'ADD_ACTIVITY'
export const LIKE_UNLIKE = 'LIKE_UNLIKE'
